@startuml
skinparam linetype ortho
title AWS Infrastructure - Deployment Diagram

' ====== AWS ======
node "AWS Services" {
  node "Recognition Service" {
    component "Recognition API"
  }


  node "Public Subnet" {
    node "EC2 Instance" {
      component "MQTT Broker"
      component "App"
    }
  }

  node "Private Subnet" {
    node "EC2 - DB server" {
      database "DB"
    }
  }
}


' ====== EXTERNO ======
node "ESP32 Device" {
  component "ESP32"
}

cloud "Internet"


' ====== RELACIONES ======

ESP32 --> "MQTT Broker" : MQTT

"MQTT Broker" --> "App" : MQTT

"App" -l-> "DB"

"App" --> "Recognition API": API

"Internet" -l-> "App" : HTTP

@enduml
