; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
platform = espressif32
framework = arduino
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
build_flags = 
	-std=c++17
	-I include
	-I include/config
	-I lib/sensors
	-I lib/tasks
	-I lib/events
	-I lib/relay
	-I lib/led
    -D MQTT_MAX_PACKET_SIZE=65535
lib_deps = 
	knolleary/PubSubClient
	adafruit/Adafruit NeoPixel@^1.15.4

[env:esp32-actor]
extends = common
board = esp32doit-devkit-v1
build_flags = 
    ${common.build_flags}
    -D DEVICE_ROLE_ACTOR

[env:esp32-camera]
extends = common
board = esp32cam
build_flags = 
    ${common.build_flags}
    -I lib/camera
    -D DEVICE_ROLE_CAMERA
